version: "{build}"
build: off
shallow_clone: true
skip_tags: true

environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"
    - nodejs_version: "7"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g i npm@latest
  - set PATH=%APPDATA%\npm;%PATH%;%APPVEYOR_BUILD_FOLDER%\node_modules\.bin
  - npm i

test_script:
  - node --version
  - npm --version
  - npm test
